### ISSUE TITLE
Error after adding equipment

### ISSUE THREAD

**Issue by Borenson** [Elytherion/tdeheroes#134]
The following error occurred after adding "Zügel und Zaumzeug" to the equipment while finishing character creation. The error message is still there when reopening the application (version 0.51.9 on Mac OS). In the character sheet, the item shows in the list of equipped items. However, I'm now not able to further edit my euipment.

ERROR
TypeError: Cannot read property 'localeCompare' of undefined
    at /Applications/TDE5 Heroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:153:54
    at list.sort (/Applications/TDE5 Heroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:28:28)
    at Array.sort (native)
    at sortObjects (/Applications/TDE5 Heroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:26:17)
    at Object.filterAndSortObjects (/Applications/TDE5 Heroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:92:12)
    at exports.getFilteredItems.reselect_1.createSelector (/Applications/TDE5 Heroes.app/Contents/Resources/app.asar/app/selectors/equipmentSelectors.js:100:30)
    at /Applications/TDE5 Heroes.app/Contents/Resources/app.asar/node_modules/reselect/lib/index.js:76:25
    at /Applications/TDE5 Heroes.app/Contents/Resources/app.asar/node_modules/reselect/lib/index.js:36:25
    at /Applications/TDE5 Heroes.app/Contents/Resources/app.asar/node_modules/reselect/lib/index.js:90:33
    at Object.getFilteredItems (/Applications/TDE5 Heroes.app/Contents/Resources/app.asar/node_modules/reselect/lib/index.js:36:25)
COMPONENT STACK

    in Connect(Equipment) (created by Route)
    in Route (created by App)
    in section (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider

**Comment by Elytherion** [comment]
Should be fixed in the next update. Please check and reopen this issue if that's not the case for you, though.
