### ISSUE TITLE
"Schrift kaufen (Kusliker Zeichen)" ticks "Chuchas" writing system 

### ISSUE THREAD

**Issue by Stemw3** [Elytherion/tdeheroes#35]
Version 0.48.1

My steps to the error: Create new Character -> Spezies: Mittelländer -> Kultur: Mittelreicher -> Profession: Krötenhexe.

Error Description:
The "Schrift kaufen (Kusliker Zeichen)", when ticked, does tick the "Chuchas"-Writing System instead of the "Kusliker Zeichen"-Writing System.
Before:
![before](https://user-images.githubusercontent.com/9552107/28546954-e1f7eea2-70cc-11e7-93b0-0628d5af0f15.png)
After:
![after](https://user-images.githubusercontent.com/9552107/28546955-e82499b0-70cc-11e7-91f4-69e68c499e2a.png)

(Edit: After reading through the "Werte werden falsch berechnet"-Issue again, I'm not sure wether or not point 1-3 are intentional or not, I'll leave them here because of that... Point 4 and definitely Point 5 should be unintentional though... )
This leads to the following things:
1. The AP for the languages and writing system doesn't get subtracted from the Profession (I still have 6 AP left). At least from my knowledge the writing system from the culture should count to the maximum from the profession.

2. If I add a writing system or language from the list before ticking the one from the culture-packet, it gets greyed out even though I have enough AP left:
![grey](https://user-images.githubusercontent.com/9552107/28547374-d9dcfec2-70ce-11e7-8785-175b505b3c07.png)

3. When this gets ignored and I proceed making the charakter, it still applies the "Kusliker Zeichen"
 though. Here you can also see once more that I was now able to pick writing systems for 8AP instead of 6AP because of the first issue:
![sonder](https://user-images.githubusercontent.com/9552107/28547268-693963c2-70ce-11e7-9465-2481ed550704.png)

4. The "Kusliker Zeichen" writing system can be ticked from the list a second time (although it will still only add 1 "Kusliker Zeichen" writing system later on and also doesn't produce an error in the console).

5.  If I use a Profession that doesn't have 6AP for languages and writing systems (e.g. "Eulenhexe"), when I tick the "Schrift kaufen (Kusliker Zeichen)" and thus the 6AP-Chuchas gets ticked, the "Fertigstellen"-Button gives an Exception:
`bundle.js:33196 Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.add [as d] (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:33196:48)
    at ListStoreStatic.addSR (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:502:96)
    at skillRatingList.forEach (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:772:54)
    at Map.forEach (native)
    at ListStoreStatic.assignRCP (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:772:25)
    at Object.ListStoreStatic.dispatchToken.__WEBPACK_IMPORTED_MODULE_3__dispatcher_AppDispatcher__.a.register [as ID_16] (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:271:30)
    at Dispatcher._invokeCallback (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:44184:24)
    at Dispatcher.waitFor (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:44144:12)
    at Object.APStoreStatic.dispatchToken.__WEBPACK_IMPORTED_MODULE_1__dispatcher_AppDispatcher__.a.register [as ID_8] (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:2645:106)
    at Dispatcher._invokeCallback (file:///E:/OneDrive/Das%20Schwarze%20Auge/DSA-Tool/tdeheroes-win32-x64/resources/app.asar/resources/bundle.js:44184:24)
add @ bundle.js:33196
addSR @ bundle.js:502
skillRatingList.forEach @ bundle.js:772
assignRCP @ bundle.js:772
ListStoreStatic.dispatchToken.__WEBPACK_IMPORTED_MODULE_3__dispatcher_AppDispatcher__.a.register @ bundle.js:271
_invokeCallback @ bundle.js:44184
waitFor @ bundle.js:44144
APStoreStatic.dispatchToken.__WEBPACK_IMPORTED_MODULE_1__dispatcher_AppDispatcher__.a.register @ bundle.js:2645
_invokeCallback @ bundle.js:44184
dispatch @ bundle.js:44160
setSelections @ bundle.js:25410
Selections.assignRCPEntries @ bundle.js:39500
ReactErrorUtils.invokeGuardedCallback @ react-dom.js:9073
executeDispatch @ react-dom.js:3031
executeDispatchesInOrder @ react-dom.js:3054
executeDispatchesAndRelease @ react-dom.js:2456
executeDispatchesAndReleaseTopLevel @ react-dom.js:2467
forEachAccumulated @ react-dom.js:15515
processEventQueue @ react-dom.js:2670
runEventQueueInBatch @ react-dom.js:9097
handleTopLevel @ react-dom.js:9108
handleTopLevelImpl @ react-dom.js:9185
perform @ react-dom.js:14816
batchedUpdates @ react-dom.js:8862
batchedUpdates @ react-dom.js:12944
dispatchEvent @ react-dom.js:9260`

**Comment by Elytherion** [comment]
I agree, 4 and 5 are bugs, but 1-3 are intentional. This is due to the fact the culture system and the profession system are not coupled in this case. So either you have to be able to add the script as a part of the profession-given AP for languages/scripts or you have to be able to add the script as a part of the culture hence no impact on the profession-given AP.

**Comment by Elytherion** [comment]
Fixed for 0.49.0. (Why didnt I just use `Array#find`?? -.-)
