### ISSUE TITLE
Exporting to PDF not possible.

### ISSUE THREAD

**Issue by Stemw3** [Elytherion/tdeheroes#47]
tl:dr.: "Exporting to PDF" creates a blank pdf.

Das Erstellen einer PDF aus dem Helden erzeugt bei mir eine PDF mit 1kb größe, welche nur aus einer einzelnen schwarzen Seite besteht. Die Konsole gibt mir diesen Fehler:
```
E:\OneDrive\Das Schwarze Auge\DSA-Tool\DSA-Tool\resources\app.asar\app\utils\createOverlay.js:7 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Object.close (E:\OneDrive\Das Schwarze Auge\DSA-Tool\DSA-Tool\resources\app.asar\app\utils\createOverlay.js:7:19)
    at electron_1.remote.globalShortcut.register (E:\OneDrive\Das Schwarze Auge\DSA-Tool\DSA-Tool\resources\app.asar\app\utils\alert.js:22:29)
    at CallbacksRegistry.apply (E:\OneDrive\Das Schwarze Auge\DSA-Tool\DSA-Tool\resources\electron.asar\common\api\callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (E:\OneDrive\Das Schwarze Auge\DSA-Tool\DSA-Tool\resources\electron.asar\renderer\api\remote.js:299:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by Elytherion** [comment]
I fixed this problem, but I still havent figured out why there is always a blank page added.
